
@startuml
left to right direction
actor Customer
actor "Post Office Staff" as Staff
actor Shipper
actor Admin

rectangle "Logistics System" {
  usecase "Register / Login" as UC1
  usecase "Create Parcel" as UC2
  usecase "Apply Promotion" as UC3
  usecase "Track Parcel" as UC4
  usecase "Pay Shipping Fee (Online/Counter)" as UC5
  usecase "Receive & Scan at Origin" as UC6
  usecase "Sort / Transfer Between Offices" as UC7
  usecase "Assign Shipper" as UC8
  usecase "Out For Delivery" as UC9
  usecase "Deliver / Fail Delivery" as UC10
  usecase "Collect COD" as UC11
  usecase "Manage Users/Roles" as UC12
  usecase "Manage Offices/Vehicles" as UC13
  usecase "Reports / Revenue" as UC14
}

Customer --> UC1
Customer --> UC2
Customer --> UC3
Customer --> UC4
Customer --> UC5

Staff --> UC6
Staff --> UC7
Staff --> UC8

Shipper --> UC9
Shipper --> UC10
Shipper --> UC11
Shipper --> UC4

Admin --> UC12
Admin --> UC13
Admin --> UC14

UC2 .> UC3 : <<include>>
UC6 .> UC7 : <<include>>
UC8 .> UC9 : <<include>>
UC9 .> UC10 : <<include>>
@enduml
